package com.royarn.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Good implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.name
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.tag_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.shop_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.price
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good.remark
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.id
     *
     * @return the value of t_good.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.id
     *
     * @param id the value for t_good.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.name
     *
     * @return the value of t_good.name
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.name
     *
     * @param name the value for t_good.name
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.tag_id
     *
     * @return the value of t_good.tag_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.tag_id
     *
     * @param tagId the value for t_good.tag_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.shop_id
     *
     * @return the value of t_good.shop_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.shop_id
     *
     * @param shopId the value for t_good.shop_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.price
     *
     * @return the value of t_good.price
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.price
     *
     * @param price the value for t_good.price
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good.remark
     *
     * @return the value of t_good.remark
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good.remark
     *
     * @param remark the value for t_good.remark
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}