package com.royarn.api.entity;

import java.io.Serializable;

public class Store implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.good_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.num
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.id
     *
     * @return the value of t_store.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.id
     *
     * @param id the value for t_store.id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.good_id
     *
     * @return the value of t_store.good_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.good_id
     *
     * @param goodId the value for t_store.good_id
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.num
     *
     * @return the value of t_store.num
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.num
     *
     * @param num the value for t_store.num
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}